import { Queue, Worker, Job } from 'bullmq';
import { prisma } from '../config/database';
import { logger } from '../utils/logger';

const QUEUE_PREFIX = 'xyvmkurmut';

function getConn() {
  return {
    host: process.env.REDIS_HOST || '127.0.0.1',
    port: parseInt(process.env.REDIS_PORT || '6379'),
    username: process.env.REDIS_USERNAME || undefined,
    password: process.env.REDIS_PASSWORD || undefined,
    maxRetriesPerRequest: null as null,
    enableReadyCheck: false,
  };
}

const defaultOpts = {
  attempts: 3,
  backoff: { type: 'exponential' as const, delay: 5000 },
  removeOnComplete: 50,
  removeOnFail: 200,
};

// ─── Queues ───────────────────────────────────────────────────────────────────
export const iplQuestionGenQueue = new Queue('ipl-question-generation', {
  connection: getConn(), prefix: QUEUE_PREFIX, defaultJobOptions: defaultOpts,
});

export const iplContestUnlockQueue = new Queue('ipl-contest-unlock', {
  connection: getConn(), prefix: QUEUE_PREFIX, defaultJobOptions: defaultOpts,
});

export const iplMatchMonitorQueue = new Queue('ipl-match-monitor', {
  connection: getConn(), prefix: QUEUE_PREFIX, defaultJobOptions: defaultOpts,
});

export const iplResultVerifyQueue = new Queue('ipl-result-verify', {
  connection: getConn(), prefix: QUEUE_PREFIX, defaultJobOptions: defaultOpts,
});

export const iplScoreCalcQueue = new Queue('ipl-score-calc', {
  connection: getConn(), prefix: QUEUE_PREFIX, defaultJobOptions: defaultOpts,
});

export const iplNotifQueue = new Queue('ipl-notifications', {
  connection: getConn(), prefix: QUEUE_PREFIX, defaultJobOptions: defaultOpts,
});

// ─── Log helper ───────────────────────────────────────────────────────────────
async function logJob(jobType: string, status: string, message: string, matchId?: string, data?: any) {
  try {
    await prisma.automationLog.create({ data: { jobType, status, message, matchId, data } });
  } catch { /* non-critical */ }
}

// ─── Workers ──────────────────────────────────────────────────────────────────

export function startIPLWorkers() {
  const conn = getConn();

  // Question generation worker
  const qGenWorker = new Worker('ipl-question-generation', async (job: Job) => {
    const { matchId } = job.data;
    try {
      const match = await prisma.iplMatch.findUnique({ where: { id: matchId } });
      if (!match) throw new Error('Match not found');
      if (match.questionsGenerated) {
        logger.info(`Questions already generated for match ${matchId}`);
        return;
      }

      const { generateQuestionsWithContext } = await import('../services/claudeAiService');
      const questions = await generateQuestionsWithContext({
        team1: match.team1, team2: match.team2,
        date: match.matchDate.toDateString(),
        venue: match.venue ?? 'TBD',
        team1Players: Array.isArray(match.team1Players) ? match.team1Players as string[] : undefined,
        team2Players: Array.isArray(match.team2Players) ? match.team2Players as string[] : undefined,
      });

      // Delete existing auto-generated and recreate
      await prisma.iplQuestion.deleteMany({ where: { matchId, isAutoGenerated: true } });

      for (let i = 0; i < questions.length; i++) {
        const q = questions[i];
        await prisma.iplQuestion.create({
          data: {
            matchId, question: q.question, options: q.options,
            correctAnswer: q.correctAnswer || '',
            points: q.points || 100,
            category: q.category || 'prediction',
            difficulty: q.difficulty || 'medium',
            status: 'active', isAutoGenerated: true,
            generatedBy: 'claude-ai', approved: false,
            questionNumber: i + 1,
            questionContext: (q as any).questionContext || null,
          },
        });
      }

      await prisma.iplMatch.update({
        where: { id: matchId },
        data: { questionsGenerated: true, lastSyncedAt: new Date() },
      });

      await logJob('QUESTION_GEN', 'SUCCESS', `Generated ${questions.length} questions`, matchId);
      logger.info(`Generated ${questions.length} questions for match ${matchId}`);
    } catch (err: any) {
      await logJob('QUESTION_GEN', 'FAILED', err.message, matchId);
      throw err;
    }
  }, { connection: conn, prefix: QUEUE_PREFIX });

  // Contest unlock worker
  const unlockWorker = new Worker('ipl-contest-unlock', async (job: Job) => {
    const { matchId } = job.data;
    try {
      const contests = await prisma.iplContest.findMany({
        where: { matchId, status: 'draft' },
        include: { entries: { select: { userId: true } } },
      });

      for (const contest of contests) {
        await prisma.iplContest.update({
          where: { id: contest.id },
          data: { status: 'published' },
        });

        // Notify joined users
        if (contest.entries.length > 0) {
          const { sendBulkNotification } = await import('../services/notificationService');
          await sendBulkNotification(
            contest.entries.map(e => e.userId),
            'Contest is LIVE!',
            `Predict now for ${contest.name}! Contest closes soon.`,
            'CONTEST_UNLOCK'
          ).catch(() => {});
        }
      }

      await logJob('CONTEST_UNLOCK', 'SUCCESS', `Unlocked ${contests.length} contests`, matchId);
    } catch (err: any) {
      await logJob('CONTEST_UNLOCK', 'FAILED', err.message, matchId);
      throw err;
    }
  }, { connection: conn, prefix: QUEUE_PREFIX });

  // Result verification worker
  const resultWorker = new Worker('ipl-result-verify', async (job: Job) => {
    const { matchId } = job.data;
    try {
      const { verifyMatchResults } = await import('../jobs/iplQuizJob');
      await verifyMatchResults(matchId);
      await prisma.iplMatch.update({
        where: { id: matchId },
        data: { resultVerified: true, resultPostedAt: new Date(), autoProcessed: true },
      });
      // Trigger score calculation
      await iplScoreCalcQueue.add('calculateScores', { matchId });
      await logJob('RESULT_VERIFY', 'SUCCESS', 'Results verified and scores queued', matchId);
    } catch (err: any) {
      await logJob('RESULT_VERIFY', 'FAILED', err.message, matchId);
      throw err;
    }
  }, { connection: conn, prefix: QUEUE_PREFIX });

  // Score calculation worker
  const scoreWorker = new Worker('ipl-score-calc', async (job: Job) => {
    const { matchId } = job.data;
    try {
      const entries = await prisma.iplContestEntry.findMany({
        where: { contest: { matchId } },
        include: { contest: true },
      });

      // Group by contest
      const byContest = new Map<string, typeof entries>();
      for (const e of entries) {
        if (!byContest.has(e.contestId)) byContest.set(e.contestId, []);
        byContest.get(e.contestId)!.push(e);
      }

      for (const [contestId, contestEntries] of byContest) {
        // Get points per user (sum of correct predictions for this match)
        const matchPredictions = await prisma.iplPrediction.findMany({
          where: { matchId, userId: { in: contestEntries.map(e => e.userId) } },
        });

        const userPoints = new Map<string, number>();
        for (const p of matchPredictions) {
          userPoints.set(p.userId, (userPoints.get(p.userId) || 0) + p.pointsEarned);
        }

        // Sort by points desc
        const sorted = contestEntries
          .map(e => ({ ...e, pts: userPoints.get(e.userId) || 0 }))
          .sort((a, b) => b.pts - a.pts);

        // Assign ranks and update
        for (let i = 0; i < sorted.length; i++) {
          await prisma.iplContestEntry.update({
            where: { id: sorted[i].id },
            data: { totalPoints: sorted[i].pts, rank: i + 1 },
          });
        }

        await prisma.iplContest.update({
          where: { id: contestId }, data: { status: 'completed' },
        });
      }

      await logJob('SCORE_CALC', 'SUCCESS', `Scores calculated for ${entries.length} entries`, matchId);
    } catch (err: any) {
      await logJob('SCORE_CALC', 'FAILED', err.message, matchId);
      throw err;
    }
  }, { connection: conn, prefix: QUEUE_PREFIX });

  // Match monitor worker — runs every 5 min during match, detects match end, queues result verification
  const monitorWorker = new Worker('ipl-match-monitor', async (job: Job) => {
    const { matchId } = job.data;
    try {
      const match = await prisma.iplMatch.findUnique({ where: { id: matchId } });
      if (!match) return;
      if (match.resultVerified) {
        logger.info(`Match ${matchId} already verified, skipping monitor`);
        return;
      }

      // Set to live if not already
      if (match.status === 'upcoming') {
        await prisma.iplMatch.update({ where: { id: matchId }, data: { status: 'live' } });
      }

      // Find real CricAPI match ID if we only have a placeholder
      let cricApiMatchId = match.cricApiId;
      if (!cricApiMatchId || cricApiMatchId.startsWith('ipl2026-match-')) {
        const { fetchTodayMatchesCricAPI } = await import('../services/cricketService');
        const todayMatches = await fetchTodayMatchesCricAPI();
        const found = todayMatches.find((m: any) => {
          const name = (m.name || '').toLowerCase();
          return (
            name.includes(match.team1.toLowerCase()) ||
            name.includes(match.team2.toLowerCase())
          );
        });
        if (found?.id) {
          cricApiMatchId = found.id;
          await prisma.iplMatch.update({ where: { id: matchId }, data: { cricApiId: cricApiMatchId } });
          logger.info(`Linked CricAPI ID ${cricApiMatchId} to match ${matchId}`);
        }
      }

      if (!cricApiMatchId || cricApiMatchId.startsWith('ipl2026-match-')) {
        await logJob('MATCH_MONITOR', 'PENDING', 'Waiting for CricAPI match ID', matchId);
        return;
      }

      const { isMatchEnded } = await import('../services/cricketService');
      const ended = await isMatchEnded(cricApiMatchId);

      if (ended) {
        logger.info(`Match ${matchId} ended — queuing result verification`);
        await iplResultVerifyQueue.add('verifyResults', { matchId }, { jobId: `result-${matchId}` });
        await logJob('MATCH_MONITOR', 'SUCCESS', 'Match ended, verification queued', matchId);
      } else {
        logger.info(`Match ${matchId} still in progress`);
      }
    } catch (err: any) {
      await logJob('MATCH_MONITOR', 'FAILED', err.message, matchId);
      throw err;
    }
  }, { connection: conn, prefix: QUEUE_PREFIX });

  // Error handlers — must handle 'error' event or Node.js throws uncaught exception
  for (const w of [qGenWorker, unlockWorker, monitorWorker, resultWorker, scoreWorker]) {
    w.on('failed', (job, err) => logger.error(`IPL worker failed`, { queue: job?.queueName, err: err.message }));
    w.on('error', (err) => logger.warn(`IPL worker error (Redis may be unavailable)`, { err: err.message }));
  }

  // Queue-level error handlers
  for (const q of [iplQuestionGenQueue, iplContestUnlockQueue, iplMatchMonitorQueue, iplResultVerifyQueue, iplScoreCalcQueue, iplNotifQueue]) {
    q.on('error', (err) => logger.warn(`IPL queue error`, { err: err.message }));
  }

  logger.info('IPL BullMQ workers started');
  return [qGenWorker, unlockWorker, monitorWorker, resultWorker, scoreWorker];
}

// ─── Schedule helpers ─────────────────────────────────────────────────────────

export async function scheduleMatchJobs(matchId: string, matchDate: Date): Promise<void> {
  const now = Date.now();
  const matchTime = matchDate.getTime();

  // Generate questions 24hrs before match
  const qDelay = Math.max(0, matchTime - 24 * 3600 * 1000 - now);
  await iplQuestionGenQueue.add('generateQuestions', { matchId }, { delay: qDelay });

  // Unlock contest 4hrs before match
  const unlockDelay = Math.max(0, matchTime - 4 * 3600 * 1000 - now);
  await iplContestUnlockQueue.add('unlockContest', { matchId }, { delay: unlockDelay });

  // Monitor match starting from match time
  const monitorDelay = Math.max(0, matchTime - now);
  await iplMatchMonitorQueue.add('monitorMatch', { matchId }, {
    delay: monitorDelay,
    repeat: { every: 5 * 60 * 1000, limit: 60 }, // every 5 mins, max 5hrs
  });

  logger.info(`Scheduled jobs for match ${matchId} at ${matchDate.toISOString()}`);
}
