import cron from 'node-cron';
import { prisma } from '../config/database';
import { getTodayIPLMatches } from '../services/cricApiService';
import { isMatchEnded, fetchMatchScorecard } from '../services/cricketService';
import { generateIPLQuestions, verifyAnswersWithAI } from '../services/claudeAiService';
import { creditCoins } from '../services/coinService';
import { logger } from '../utils/logger';
import { sendDailyBonusReminders } from '../services/oneSignalService';

// Runs every day at 8 AM — generates quiz questions for today's IPL matches
export function scheduleQuizGeneration(): void {
  cron.schedule('0 8 * * *', async () => {
    logger.info('Starting IPL quiz generation job...');
    try {
      await generateQuestionsForTodayMatches();
    } catch (err) {
      logger.error('Quiz generation job failed:', err);
    }
  });
  logger.info('IPL quiz generation job scheduled (daily at 08:00)');
}

// Runs at 9 AM and 7 PM daily — reminds users to claim their daily bonus
export function scheduleDailyBonusReminders(): void {
  cron.schedule('0 9 * * *', async () => {
    logger.info('Sending daily bonus reminders (9 AM)...');
    await sendDailyBonusReminders();
  });
  cron.schedule('0 19 * * *', async () => {
    logger.info('Sending daily bonus reminders (7 PM)...');
    await sendDailyBonusReminders();
  });
  logger.info('Daily bonus reminder jobs scheduled (09:00 and 19:00)');
}

// Runs every hour — checks completed matches and credits coins to correct predictors
export function scheduleResultVerification(): void {
  cron.schedule('0 * * * *', async () => {
    logger.info('Checking IPL match results...');
    try {
      await verifyCompletedMatches();
    } catch (err) {
      logger.error('Result verification job failed:', err);
    }
  });
  logger.info('IPL result verification job scheduled (hourly)');
}

// ─── Core Logic (also called from admin controller for manual triggers) ────────

export async function generateQuestionsForTodayMatches(): Promise<number> {
  const matches = await getTodayIPLMatches();
  let generated = 0;

  for (const match of matches) {
    if (!match.team1 || !match.team2) continue;

    // Skip if questions already exist for this Cricbuzz match
    const existing = await prisma.iplQuestion.findFirst({
      where: { match: { cricApiId: match.id?.toString() } },
    });
    if (existing) continue;

    // Find or create match record in DB
    let dbMatch = await prisma.iplMatch.findFirst({
      where: { cricApiId: match.id?.toString() },
    });

    if (!dbMatch) {
      dbMatch = await prisma.iplMatch.create({
        data: {
          matchNumber: 0,
          team1: match.team1,
          team2: match.team2,
          matchDate: match.startTime ? new Date(parseInt(match.startTime)) : new Date(),
          venue: match.venue || match.city || 'TBD',
          status: 'upcoming',
          cricApiId: match.id?.toString(),
        },
      });
    }

    // Generate questions with Claude AI
    const questions = await generateIPLQuestions({
      team1: dbMatch.team1,
      team2: dbMatch.team2,
      date: dbMatch.matchDate.toDateString(),
      venue: dbMatch.venue ?? 'TBD',
    });

    // Save to DB
    for (const q of questions) {
      await prisma.iplQuestion.create({
        data: {
          matchId: dbMatch.id,
          question: q.question,
          options: q.options,
          correctAnswer: q.correctAnswer || '',
          points: q.points || 100,
          status: 'active',
          isAutoGenerated: true,
          generatedBy: 'claude-ai',
        },
      });
    }

    logger.info(
      `Generated ${questions.length} questions for ${dbMatch.team1} vs ${dbMatch.team2}`
    );
    generated += questions.length;
  }

  return generated;
}

export async function verifyMatchResults(matchId: string): Promise<void> {
  const match = await prisma.iplMatch.findUnique({
    where: { id: matchId },
    include: { questions: true },
  });

  if (!match || !match.cricApiId) {
    throw new Error('Match not found or has no CricAPI ID');
  }

  // Use CricAPI (not Cricbuzz) for result checking
  const ended = await isMatchEnded(match.cricApiId);
  if (!ended) {
    throw new Error('Match has not ended yet');
  }

  const scorecard = await fetchMatchScorecard(match.cricApiId);
  if (!scorecard) {
    throw new Error('Could not fetch scorecard from CricAPI');
  }

  // Parse CricAPI scorecard format
  const statusText: string = scorecard.status || '';
  const teamInfo: any[] = scorecard.teamInfo || [];
  const scores: any[] = scorecard.score || [];

  // Extract winner from status string e.g. "CSK won by 5 wickets"
  let winner = '';
  for (const team of teamInfo) {
    const n = team.name || '';
    const s = team.shortname || '';
    if (
      (n && statusText.toLowerCase().includes(n.toLowerCase())) ||
      (s && statusText.toLowerCase().includes(s.toLowerCase()))
    ) {
      winner = n || s;
      break;
    }
  }
  if (!winner) {
    if (statusText.toLowerCase().includes(match.team1.toLowerCase())) winner = match.team1;
    else if (statusText.toLowerCase().includes(match.team2.toLowerCase())) winner = match.team2;
  }

  const team1Score = scores[0] ? `${scores[0].r}/${scores[0].w}` : undefined;
  const team2Score = scores[1] ? `${scores[1].r}/${scores[1].w}` : undefined;

  // Update match status
  await prisma.iplMatch.update({
    where: { id: match.id },
    data: {
      status: 'completed',
      result: statusText || winner,
      winnerId: winner,
      team1Score,
      team2Score,
    },
  });

  // Verify answers with Claude AI
  const verifiedQuestions = await verifyAnswersWithAI(match.questions, {
    winner,
    team1Score: scores[0]?.r,
    team2Score: scores[1]?.r,
  });

  // Update correct answers
  for (const q of verifiedQuestions) {
    if (q.id && q.correctAnswer) {
      await prisma.iplQuestion.update({
        where: { id: q.id as string },
        data: { correctAnswer: q.correctAnswer as string },
      });
    }
  }

  // Credit coins to correct predictors
  const predictions = await prisma.iplPrediction.findMany({
    where: { matchId: match.id },
  });

  for (const pred of predictions) {
    const question = verifiedQuestions.find((q: any) => q.id === pred.questionId);
    if (!question?.correctAnswer) continue;

    const isCorrect = pred.answer === question.correctAnswer;
    const pointsEarned = isCorrect ? (question.points as number) : 0;

    await prisma.iplPrediction.update({
      where: { id: pred.id },
      data: { isCorrect, pointsEarned },
    });

    if (isCorrect) {
      await creditCoins(
        pred.userId,
        pointsEarned,
        'EARN_IPL_WIN',
        pred.id,
        `IPL prediction correct: ${question.question as string}`
      );
    }
  }

  logger.info(`Results processed for match: ${match.team1} vs ${match.team2}`);
}

// Runs every minute — notifies users when contest questions go live
export function scheduleQuestionNotifications(): void {
  cron.schedule('* * * * *', async () => {
    try {
      const now = new Date();
      const oneMinuteAgo = new Date(now.getTime() - 60000);

      const contests = await prisma.iplContest.findMany({
        where: {
          questionsAvailableAt: { gte: oneMinuteAgo, lte: now },
          status: 'published',
        },
        include: {
          match: true,
          entries: { select: { userId: true } },
        },
      });

      for (const contest of contests) {
        if (contest.entries.length === 0) continue;
        const userIds = contest.entries.map(e => e.userId);
        try {
          const { sendBulkNotification } = await import('../services/notificationService');
          await sendBulkNotification(
            userIds,
            'Questions are LIVE!',
            `Predict now for ${contest.match.team1} vs ${contest.match.team2}! Contest: ${contest.name}`,
            'IPL_QUESTIONS_LIVE'
          );
        } catch { /* non-critical */ }
        logger.info(`Question notifications sent for contest: ${contest.name}`);
      }
    } catch (err) {
      logger.error('Question notification job error:', err);
    }
  });
  logger.info('Question notification job scheduled (every minute)');
}

async function verifyCompletedMatches(): Promise<void> {
  const liveMatches = await prisma.iplMatch.findMany({
    where: { status: 'live', cricApiId: { not: null } },
    include: { questions: true },
  });

  for (const match of liveMatches) {
    try {
      await verifyMatchResults(match.id);
    } catch (err) {
      // Log but continue processing other matches
      logger.warn(`Result verification skipped for match ${match.id}:`, err);
    }
  }
}
