import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding QuizSettings...');

  await prisma.quizSettings.upsert({
    where: { id: 1 },
    update: {},
    create: {
      id: 1,
      ticketPerStage: 1,
      bonusTicketEnabled: true,
      maxHintsPerStage: 3,
      dailyTicketLimit: 20,
      cooldownMinutes: 30,
      sessionExpiryMinutes: 15,
      minAnswerTimeMs: 2000,
      minSessionTimeMs: 20000,
      questionsPerStage: 10,
      aiGenerationEnabled: true,
    },
  });

  console.log('QuizSettings seeded.');
  console.log('Seeding 30 SportsQuestions...');

  await prisma.sportsQuestion.createMany({
    skipDuplicates: true,
    data: [
      // ─── IPL (8) ───────────────────────────────────────────────────────────
      {
        question: 'Which team won IPL 2024?',
        optionA: 'MI',
        optionB: 'KKR',
        optionC: 'CSK',
        optionD: 'RCB',
        correctOption: 'B',
        explanation: 'KKR won their 3rd IPL title in 2024 defeating SRH',
        sport: 'ipl',
        difficulty: 'easy',
      },
      {
        question: 'Who has scored most runs in IPL history?',
        optionA: 'Rohit Sharma',
        optionB: 'David Warner',
        optionC: 'Virat Kohli',
        optionD: 'Shikhar Dhawan',
        correctOption: 'C',
        explanation: 'Virat Kohli has scored 7000+ runs in IPL history',
        sport: 'ipl',
        difficulty: 'easy',
      },
      {
        question: 'IPL was first played in which year?',
        optionA: '2006',
        optionB: '2007',
        optionC: '2008',
        optionD: '2009',
        correctOption: 'C',
        explanation: 'IPL began in 2008, first won by Rajasthan Royals',
        sport: 'ipl',
        difficulty: 'easy',
      },
      {
        question: 'Which team won the first IPL in 2008?',
        optionA: 'Mumbai Indians',
        optionB: 'Chennai Super Kings',
        optionC: 'Rajasthan Royals',
        optionD: 'Kolkata Knight Riders',
        correctOption: 'C',
        explanation: 'Rajasthan Royals under Shane Warne won inaugural IPL',
        sport: 'ipl',
        difficulty: 'easy',
      },
      {
        question: 'Who won Purple Cap in IPL 2024?',
        optionA: 'Jasprit Bumrah',
        optionB: 'Yuzvendra Chahal',
        optionC: 'Anrich Nortje',
        optionD: 'Matheesha Pathirana',
        correctOption: 'D',
        explanation: 'Matheesha Pathirana won Purple Cap with 24 wickets',
        sport: 'ipl',
        difficulty: 'medium',
      },
      {
        question: 'Highest individual score in IPL history?',
        optionA: '158*',
        optionB: '175*',
        optionC: '172*',
        optionD: '162*',
        correctOption: 'B',
        explanation: 'Brendon McCullum scored 175* for KKR in IPL 2008',
        sport: 'ipl',
        difficulty: 'hard',
      },
      {
        question: 'Which team has appeared in most IPL finals?',
        optionA: 'Mumbai Indians',
        optionB: 'Chennai Super Kings',
        optionC: 'Kolkata Knight Riders',
        optionD: 'Royal Challengers Bangalore',
        correctOption: 'B',
        explanation: 'CSK has appeared in 10 IPL finals, most by any team',
        sport: 'ipl',
        difficulty: 'medium',
      },
      {
        question: 'Which team has won most IPL titles?',
        optionA: 'Mumbai Indians',
        optionB: 'Chennai Super Kings',
        optionC: 'Kolkata Knight Riders',
        optionD: 'Sunrisers Hyderabad',
        correctOption: 'A',
        explanation: 'Mumbai Indians have won 5 IPL titles, most ever',
        sport: 'ipl',
        difficulty: 'easy',
      },
      // ─── Cricket (5) ───────────────────────────────────────────────────────
      {
        question: 'Who holds record for most Test centuries?',
        optionA: 'Ricky Ponting',
        optionB: 'Sachin Tendulkar',
        optionC: 'Virat Kohli',
        optionD: 'Jacques Kallis',
        correctOption: 'B',
        explanation: 'Sachin Tendulkar has 51 Test centuries',
        sport: 'cricket',
        difficulty: 'easy',
      },
      {
        question: 'Which country won Cricket World Cup 2023?',
        optionA: 'India',
        optionB: 'Australia',
        optionC: 'England',
        optionD: 'South Africa',
        correctOption: 'B',
        explanation: 'Australia beat India in ODI World Cup 2023 final',
        sport: 'cricket',
        difficulty: 'easy',
      },
      {
        question: 'Who hit 6 sixes in an over in international cricket?',
        optionA: 'Chris Gayle',
        optionB: 'Yuvraj Singh',
        optionC: 'Rohit Sharma',
        optionD: 'Glenn Maxwell',
        correctOption: 'B',
        explanation: 'Yuvraj Singh hit 6 sixes off Stuart Broad in T20 WC 2007',
        sport: 'cricket',
        difficulty: 'medium',
      },
      {
        question: 'How many players are there in a cricket team?',
        optionA: '9',
        optionB: '10',
        optionC: '11',
        optionD: '12',
        correctOption: 'C',
        sport: 'cricket',
        difficulty: 'easy',
      },
      {
        question: 'What does LBW stand for in cricket?',
        optionA: 'Left Before Wicket',
        optionB: 'Leg Before Wicket',
        optionC: 'Low Ball Wicket',
        optionD: 'Left Bat Wicket',
        correctOption: 'B',
        sport: 'cricket',
        difficulty: 'easy',
      },
      // ─── Football (4) ──────────────────────────────────────────────────────
      {
        question: 'Which country has won most FIFA World Cups?',
        optionA: 'Germany',
        optionB: 'Argentina',
        optionC: 'Brazil',
        optionD: 'France',
        correctOption: 'C',
        explanation: 'Brazil has won 5 World Cups',
        sport: 'football',
        difficulty: 'easy',
      },
      {
        question: 'Who won FIFA World Cup 2022?',
        optionA: 'France',
        optionB: 'Brazil',
        optionC: 'Argentina',
        optionD: 'Germany',
        correctOption: 'C',
        explanation: "Argentina won WC 2022, Messi's first World Cup",
        sport: 'football',
        difficulty: 'easy',
      },
      {
        question: 'Who has won most Ballon d Or awards?',
        optionA: 'Cristiano Ronaldo',
        optionB: 'Lionel Messi',
        optionC: 'Zinedine Zidane',
        optionD: 'Ronaldinho',
        correctOption: 'B',
        explanation: 'Lionel Messi has won 8 Ballon d Or awards',
        sport: 'football',
        difficulty: 'medium',
      },
      {
        question: 'Which club has won most UEFA Champions League titles?',
        optionA: 'Barcelona',
        optionB: 'Bayern Munich',
        optionC: 'Real Madrid',
        optionD: 'Liverpool',
        correctOption: 'C',
        explanation: 'Real Madrid has won 15 Champions League titles',
        sport: 'football',
        difficulty: 'medium',
      },
      // ─── Kabaddi (3) ───────────────────────────────────────────────────────
      {
        question: 'Which team has won most PKL titles?',
        optionA: 'Patna Pirates',
        optionB: 'Jaipur Pink Panthers',
        optionC: 'Bengaluru Bulls',
        optionD: 'UP Yoddhas',
        correctOption: 'A',
        explanation: 'Patna Pirates won 3 consecutive PKL titles',
        sport: 'kabaddi',
        difficulty: 'medium',
      },
      {
        question: 'How many players are on each side in Kabaddi?',
        optionA: '5',
        optionB: '6',
        optionC: '7',
        optionD: '8',
        correctOption: 'C',
        sport: 'kabaddi',
        difficulty: 'easy',
      },
      {
        question: 'What does PKL stand for?',
        optionA: 'Pro Kabaddi League',
        optionB: 'Premier Kabaddi League',
        optionC: 'Play Kabaddi League',
        optionD: 'Pro Kho League',
        correctOption: 'A',
        sport: 'kabaddi',
        difficulty: 'easy',
      },
      // ─── Badminton (3) ─────────────────────────────────────────────────────
      {
        question: 'PV Sindhu won her first Olympic medal in which year?',
        optionA: '2012',
        optionB: '2016',
        optionC: '2021',
        optionD: '2024',
        correctOption: 'B',
        explanation: 'PV Sindhu won silver at Rio 2016 Olympics',
        sport: 'badminton',
        difficulty: 'easy',
      },
      {
        question: 'Which country dominates world badminton historically?',
        optionA: 'India',
        optionB: 'Indonesia',
        optionC: 'China',
        optionD: 'Denmark',
        correctOption: 'C',
        sport: 'badminton',
        difficulty: 'medium',
      },
      {
        question: 'Who won badminton gold at Tokyo Olympics 2020?',
        optionA: 'PV Sindhu',
        optionB: 'Tai Tzu-ying',
        optionC: 'Chen Yufei',
        optionD: 'Saina Nehwal',
        correctOption: 'C',
        explanation: 'Chen Yufei of China won gold at Tokyo 2020',
        sport: 'badminton',
        difficulty: 'medium',
      },
      // ─── Tennis (3) ────────────────────────────────────────────────────────
      {
        question: 'Who has won most Grand Slam singles titles overall?',
        optionA: 'Roger Federer',
        optionB: 'Novak Djokovic',
        optionC: 'Rafael Nadal',
        optionD: 'Pete Sampras',
        correctOption: 'B',
        explanation: 'Novak Djokovic has won 24 Grand Slam titles',
        sport: 'tennis',
        difficulty: 'medium',
      },
      {
        question: "How many sets are played in a men's Grand Slam final?",
        optionA: '3',
        optionB: '4',
        optionC: '5',
        optionD: '2',
        correctOption: 'C',
        sport: 'tennis',
        difficulty: 'easy',
      },
      {
        question: 'Which Grand Slam is played on clay courts?',
        optionA: 'Wimbledon',
        optionB: 'US Open',
        optionC: 'French Open',
        optionD: 'Australian Open',
        correctOption: 'C',
        explanation: 'French Open (Roland Garros) is played on clay',
        sport: 'tennis',
        difficulty: 'easy',
      },
      // ─── General Sports (4) ────────────────────────────────────────────────
      {
        question: 'Who won javelin gold at Tokyo Olympics 2020?',
        optionA: 'Neeraj Chopra',
        optionB: 'Devendra Jhajharia',
        optionC: 'Sumit Antil',
        optionD: 'Bajrang Punia',
        correctOption: 'A',
        explanation: "Neeraj Chopra won India's first athletics Olympic gold",
        sport: 'other',
        difficulty: 'easy',
      },
      {
        question: 'How many players are on a basketball team on court?',
        optionA: '4',
        optionB: '5',
        optionC: '6',
        optionD: '7',
        correctOption: 'B',
        sport: 'other',
        difficulty: 'easy',
      },
      {
        question: 'Which sport uses the term Grand Prix?',
        optionA: 'Tennis',
        optionB: 'Cycling',
        optionC: 'Formula 1',
        optionD: 'Swimming',
        correctOption: 'C',
        sport: 'other',
        difficulty: 'easy',
      },
      {
        question: 'India won how many medals at Paris Olympics 2024?',
        optionA: '4',
        optionB: '5',
        optionC: '6',
        optionD: '7',
        correctOption: 'C',
        explanation: 'India won 6 medals at Paris 2024 Olympics',
        sport: 'other',
        difficulty: 'medium',
      },
    ],
  });

  console.log('30 SportsQuestions seeded.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
